plugins {
    id 'java'
    id("io.qameta.allure") version "4.1.0"
}

group = 'ru.alfabank'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation("org.junit.platform:junit-platform-suite:1.10.2")

    testImplementation("io.cucumber:cucumber-java:7.33.0")
    testImplementation("io.cucumber:cucumber-junit:7.33.0")

    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.34.4")

    testImplementation("io.rest-assured:rest-assured:5.5.6")
    testImplementation("org.hamcrest:hamcrest:3.0")

    implementation("com.codeborne:selenide:7.18.1")

    testImplementation("io.qameta.allure:allure-jupiter:2.35.5")
    testImplementation 'io.qameta.allure:allure-assertj:2.35.4'
    testImplementation 'io.qameta.allure:allure-java-commons:2.35.4'
    testImplementation 'io.qameta.allure:allure-rest-assured:2.35.4'
    testImplementation 'io.qameta.allure:allure-selenide:2.35.4'
}

test {
    useJUnitPlatform()
    systemProperty("allure.results.directory", "$buildDir/allure-results")
    // чистим каталог результатов перед каждым запуском
    doFirst {
        delete "$buildDir/allure-results"
    }
}

allure {
    version = '2.27.0' // Версия Allure, которая будет использоваться для отчетов
    adapter {
        autoconfigure = true
        aspectjWeaver = true // <-- подключает agent автоматически
    }
}